version: 2.1

orbs:
  python: circleci/python@2.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Updated to a more recent Python version
    working_directory: ~/repo
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/repo
          pip-dependency-file: requirements.txt
      - run:
          name: Run linter
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest -v --cov=calculator --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results